# Generated by Django 4.2.6 on 2025-01-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_alter_mainpage_options_alter_socialmedia_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Видео на главной странице',
                'verbose_name_plural': 'Видео на главной странице',
            },
        ),
    ]
