# Generated by Django 4.2.6 on 2025-02-16 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_delete_translations'),
        ('main_page', '0003_mainpagevideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название анализа')),
                ('name_latin', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название анализа на латинице')),
            ],
            options={
                'verbose_name': 'Анализ',
                'verbose_name_plural': 'Анализы',
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название показателя')),
                ('name_latin', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название анализа на латинице')),
                ('min_value', models.PositiveIntegerField(verbose_name='Минимальное значение')),
                ('max_value', models.PositiveIntegerField(verbose_name='Максимальное значение')),
                ('unit', models.CharField(max_length=100, verbose_name='Единица измерения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='main_page.analysis', verbose_name='Анализ')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicators', to='post.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Показатель анализа',
                'verbose_name_plural': 'Показатели анализа',
            },
        ),
    ]
