# Generated by Django 4.2.6 on 2025-03-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_alter_indicator_max_value_alter_indicator_min_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpagevideo',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='./main_page/videos/', verbose_name='Обложка видео в карусели'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='max_value',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Максимальное значение'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='min_value',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Минимальное значение'),
        ),
    ]
