# Generated by Django 4.2.6 on 2024-10-06 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_rename_subscription_client_subscription_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='clientdevice',
            name='client_clie_device__c78862_idx',
        ),
    ]
