# Generated by Django 4.2.6 on 2024-10-06 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('client', '0009_remove_clientdevice_client_clie_device__c78862_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='subscription_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.subscriptiontype'),
        ),
    ]
