# Generated by Django 4.2.6 on 2025-01-15 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0011_alter_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdevice',
            name='accessible',
            field=models.BooleanField(default=False, verbose_name='Имеет доступ к аккаунту'),
        ),
        migrations.AlterField(
            model_name='clientdevice',
            name='device_id',
            field=models.CharField(editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='clientdevice',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
