# Generated by Django 4.2.6 on 2025-01-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_clientdevice_accessible_alter_clientdevice_device_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdevice',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
