# Generated by Django 4.2.6 on 2025-03-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_alter_clientdevice_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientdevice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='clientdevice',
            name='device_model',
            field=models.CharField(default=None, editable=False, max_length=128, null=True),
        ),
    ]
