# Generated by Django 4.2.6 on 2025-04-14 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_alter_clientdevice_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientdevice',
            old_name='device_model',
            new_name='model',
        ),
    ]
