# Generated by Django 4.2.6 on 2025-04-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_rename_device_model_clientdevice_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Токен для Firebase'),
        ),
    ]
