# Generated by Django 4.2.6 on 2023-11-26 10:24

from django.db import migrations, models


def set_slug(apps, schema_editor):
    Category = apps.get_model('post', 'Category')
    for category in Category.objects.all():
        category.slug = category.name.lower()
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(default='slug', max_length=256),
        ),
        migrations.RunPython(set_slug),
    ]
