# Generated by Django 4.2.6 on 2024-07-27 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_mainpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='main_post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_in_category', to='post.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='../media/main_post/', verbose_name='Обложка главного поста'),
        ),
    ]
