# Generated by Django 4.2.6 on 2024-07-27 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_category_main_post_post_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainPost',
        ),
    ]
