# Generated by Django 4.2.6 on 2024-07-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_delete_mainpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='../media/main_post/', verbose_name='Обложка главного поста'),
        ),
    ]
