# Generated by Django 4.2.6 on 2024-08-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_remove_post_img_category_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='position_in_category',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='./main_post/', verbose_name='Обложка главного поста'),
        ),
    ]
