# Generated by Django 4.2.6 on 2024-08-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_post_position_in_category_alter_category_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='position_in_category',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Позиция в категории'),
        ),
    ]
