# Generated by Django 4.2.6 on 2024-08-02 10:14

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_post_position_in_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Контент на английском'),
        ),
    ]
