# Generated by Django 4.2.6 on 2024-08-05 16:35

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_post_content_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_en',
        ),
        migrations.AlterField(
            model_name='post',
            name='content_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Контент на английском'),
        ),
    ]
