# Generated by Django 4.2.6 on 2024-08-12 16:24

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_remove_post_content_en_alter_post_content_ru'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_uz', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Контент на узбекском')),
                ('content_en', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Контент на английском')),
            ],
            options={
                'verbose_name': 'Перевод',
                'verbose_name_plural': 'Переводы',
            },
        ),
    ]
