# Generated by Django 4.2.6 on 2024-10-07 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_category_main_post2_category_main_post3_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Translations',
        ),
    ]
