# Generated by Django 4.2.6 on 2024-08-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient_group',
            field=models.CharField(blank=True, choices=[('Manager', 'Manager')], max_length=100, null=True, verbose_name='Группа получателей'),
        ),
    ]
