# Generated by Django 4.2.6 on 2024-10-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='recipient_group',
            field=models.CharField(blank=True, choices=[], max_length=100, null=True, verbose_name='Группа получателей'),
        ),
    ]
