# Generated by Django 4.2.6 on 2025-04-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_notification_recipient_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(max_length=500, verbose_name='Основной текст'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient_group',
            field=models.CharField(blank=True, choices=[('Manager', 'Manager'), ('Subscriber', 'Subscriber'), ('Member', 'Member')], max_length=100, null=True, verbose_name='Группа получателей'),
        ),
    ]
