# Generated by Django 4.2.6 on 2025-04-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_notification_title_alter_notification_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='Заголовок'),
        ),
    ]
