from transliterate.base import TranslitLanguagePack, registry
from transliterate import translit

class UzbekLanguagePack(TranslitLanguagePack):
    language_code = "uz"
    language_name = "Uzbek"
    mapping = (
        u"абвгдеёжзийклмнопрстуфхцчшщъыьэюяқғҳўАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯҚҒҲЎ",
        u"abvgdeyojziyklmnoprstufxtschshʼ'eyuyaqgʻhoʻABVGDEYOJZIYKLMNOPRSTUFXTSCHSHEYUYAQGʻHOʻ",
    )
    pre_processor_mapping = {
        #lowercase
        u"а": u"a",
        u"б": u"b",
        u"в": u"v",
        u"г": u"g",
        u"д": u"d",
        u"е": u"e",
        u"ё": u"yo",
        u"ж": u"j",
        u"з": u"z",
        u"и": u"i",
        u"й": u"y",
        u"к": u"k",
        u"л": u"l",
        u"м": u"m",
        u"н": u"n",
        u"о": u"o",
        u"п": u"p",
        u"р": u"r",
        u"с": u"s",
        u"т": u"t",
        u"у": u"u",
        u"ф": u"f",
        u"х": u"x",
        u"ц": u"ts",
        u"ч": u"ch",
        u"ш": u"sh",
        u"щ": u"sh",
        u"ъ": u"ʼ",
        u"ы": u"y",
        u"ь": u"'",
        u"э": u"e",
        u"ю": u"yu",
        u"я": u"ya",
        u"қ": u"q",
        u"ғ": u"gʻ",
        u"ҳ": u"h",
        u"ў": u"oʻ",

        # uppercase
        u"А": u"A",
        u"Б": u"B",
        u"В": u"V",
        u"Г": u"G",
        u"Д": u"D",
        u"Е": u"E",
        u"Ё": u"YO",
        u"Ж": u"J",
        u"З": u"Z",
        u"И": u"I",
        u"Й": u"Y",
        u"К": u"K",
        u"Л": u"L",
        u"М": u"M",
        u"Н": u"N",
        u"О": u"O",
        u"П": u"P",
        u"Р": u"R",
        u"С": u"S",
        u"Т": u"T",
        u"У": u"U",
        u"Ф": u"F",
        u"Х": u"X",
        u"Ц": u"TS",
        u"Ч": u"CH",
        u"Ш": u"SH",
        u"Щ": u"SH",
        u"Ъ": u"ʼ",
        u"Ы": u"Y",
        u"Ь": u"'",
        u"Э": u"E",
        u"Ю": u"YU",
        u"Я": u"YA",
        u"Қ": u"Q",
        u"Ғ": u"Gʻ",
        u"Ҳ": u"H",
        u"Ў": u"Oʻ",
    }

# Регистрируем новый языковой пакет
registry.register(UzbekLanguagePack)
